In [3]:
import pandas as pd
import sqlite3

## 2026 Australian Open

In [2]:
# QFs
# Alcaraz d. De Minaur
# Zverev d. Tien
# Djokovic d. Musetti
# Sinner d. Shelton

# SFs
# Alcaraz d. Zverev
# Djokovic d. Sinner

# Fs
# Alcaraz d. Djokovic

In [3]:
con = sqlite3.connect('../data/tennis.db')

In [5]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Alcaraz, Carlos'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,365,"Alcaraz, Carlos",13,9,8,6,2,0,0,0,...,2,2,3,3,3,2,4,3,2,2

In [45]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 14,
    QF_Wins = 10,
    SF_Wins = 9,
    F_Wins = 7,
    Aus_QF_Appears = 3,
    Aus_QF_Wins = 1,
    Aus_SF_Wins = 1,
    Aus_F_Wins = 1
    
    WHERE Player = 'Alcaraz, Carlos'
    """
)

In [7]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'De Minaur, Alex'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,272,"De Minaur, Alex",6,0,0,0,1,0,0,0,...,0,0,1,0,0,0,3,0,0,0

In [57]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 7,
    Aus_QF_Appears = 2
    
    WHERE Player = 'De Minaur, Alex'
    """
)

In [9]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Zverev, Alexander'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,77,"Zverev, Alexander",15,9,3,0,4,3,1,0,...,1,0,0,0,0,0,4,2,1,0

In [10]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 16,
    QF_Wins = 10,
    Aus_QF_Appears = 5,
    Aus_QF_Wins = 4
    
    WHERE Player = 'Zverev, Alexander'
    """
)

In [11]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Tien, Learner'
    """
    ,
    con
)

Empty DataFrame
Columns: [index, Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Aus_QF_Appears, Aus_QF_Wins, Aus_SF_Wins, Aus_F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins, Wim_QF_Appears, Wim_QF_Wins, Wim_SF_Wins, Wim_F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins]
Index: []

[0 rows x 22 columns]

In [20]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (384, 'Tien, Learner', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    """
)

In [21]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Djokovic, Novak'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,2,"Djokovic, Novak",64,53,37,24,15,12,10,10,...,7,3,16,14,10,7,14,14,10,4

In [22]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 65,
    QF_Wins = 54,
    SF_Wins = 38,
    Aus_QF_Appears = 16,
    Aus_QF_Wins = 13,
    Aus_SF_Wins = 11
    
    WHERE Player = 'Djokovic, Novak'
    """
)

In [24]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Musetti, Lorenzo'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,379,"Musetti, Lorenzo",2,2,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0

In [25]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 3,
    Aus_QF_Appears = 1
    
    WHERE Player = 'Musetti, Lorenzo'
    """
)

In [26]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Sinner, Jannik'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,343,"Sinner, Jannik",13,8,6,4,3,2,2,2,...,1,0,4,2,1,1,3,2,2,1

In [29]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 14,
    QF_Wins = 9,
    Aus_QF_Appears = 4,
    Aus_QF_Wins = 3
    
    WHERE Player = 'Sinner, Jannik'
    """
)

In [30]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Shelton, Ben'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,375,"Shelton, Ben",4,2,0,0,2,1,0,0,...,0,0,1,0,0,0,1,1,0,0

In [31]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 5,
    Aus_QF_Appears = 3
    
    WHERE Player = 'Shelton, Ben'
    """
)

In [32]:
con.commit()

In [33]:
con.close()

## 2026 French Open

In [15]:
# QFs
# Arnaldi d. Berrettini ret.
# Cobolli d. Auger-Aliassime
# Mensik d. Fonseca
# Zverev d. Jodar

# SFs
# Cobolli d. Arnaldi w/o
# Zverev d. Mensik

# Fs
# Zverev d. Cobolli

In [4]:
con = sqlite3.connect('../data/tennis.db')

In [16]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Arnaldi, Matteo'
    """
    ,
    con
)

Empty DataFrame
Columns: [index, Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Aus_QF_Appears, Aus_QF_Wins, Aus_SF_Wins, Aus_F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins, Wim_QF_Appears, Wim_QF_Wins, Wim_SF_Wins, Wim_F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins]
Index: []

[0 rows x 22 columns]

In [21]:
pd.read_sql(
    """
    SELECT rowid
    FROM mens_tennis
    ORDER BY rowid DESC
    LIMIT 10
    """
    ,
    con
)

   index
0    384
1    383
2    382
3    381
4    380
5    379
6    378
7    377
8    376
9    375

In [22]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (385, 'Arnaldi, Matteo', 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    """
)

In [24]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Mensik, Jakub'
    """
    ,
    con
)

Empty DataFrame
Columns: [index, Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Aus_QF_Appears, Aus_QF_Wins, Aus_SF_Wins, Aus_F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins, Wim_QF_Appears, Wim_QF_Wins, Wim_SF_Wins, Wim_F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins]
Index: []

[0 rows x 22 columns]

In [25]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (386, 'Mensik, Jakub', 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    """
)

In [26]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Fonseca, Joao'
    """
    ,
    con
)

Empty DataFrame
Columns: [index, Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Aus_QF_Appears, Aus_QF_Wins, Aus_SF_Wins, Aus_F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins, Wim_QF_Appears, Wim_QF_Wins, Wim_SF_Wins, Wim_F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins]
Index: []

[0 rows x 22 columns]

In [27]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (387, 'Fonseca, Joao', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    """
)

In [28]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Jodar, Rafael'
    """
    ,
    con
)

Empty DataFrame
Columns: [index, Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Aus_QF_Appears, Aus_QF_Wins, Aus_SF_Wins, Aus_F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins, Wim_QF_Appears, Wim_QF_Wins, Wim_SF_Wins, Wim_F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins]
Index: []

[0 rows x 22 columns]

In [29]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (388, 'Jodar, Rafael', 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    """
)

In [36]:
pd.read_sql(
    """
    SELECT QF_Appears, QF_Wins, SF_Wins, F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins
    FROM mens_tennis
    WHERE Player = 'Berrettini, Matteo'
    """
    ,
    con
)

,QF_Appears,QF_Wins,SF_Wins,F_Wins,Fr_QF_Appears,Fr_QF_Wins,Fr_SF_Wins,Fr_F_Wins
0,6,3,1,0,1,0,0,0

In [37]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 7,
    Fr_QF_Appears = 2
    
    WHERE Player = 'Berrettini, Matteo'
    """
)

In [38]:
pd.read_sql(
    """
    SELECT QF_Appears, QF_Wins, SF_Wins, F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins
    FROM mens_tennis
    WHERE Player = 'Cobolli, Flavio'
    """
    ,
    con
)

,QF_Appears,QF_Wins,SF_Wins,F_Wins,Fr_QF_Appears,Fr_QF_Wins,Fr_SF_Wins,Fr_F_Wins
0,1,0,0,0,0,0,0,0

In [39]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 2,
    QF_Wins = 1,
    SF_Wins = 1,
    F_Wins = 0,
    Fr_QF_Appears = 1,
    Fr_QF_Wins = 1,
    Fr_SF_Wins = 1
    
    WHERE Player = 'Cobolli, Flavio'
    """
)

In [41]:
pd.read_sql(
    """
    SELECT Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins
    FROM mens_tennis
    WHERE Player = 'Auger-Aliassime, Felix'
    """
    ,
    con
)

,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Fr_QF_Appears,Fr_QF_Wins,Fr_SF_Wins,Fr_F_Wins
0,"Auger-Aliassime, Felix",4,2,0,0,0,0,0,0

In [42]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 5,
    Fr_QF_Appears = 1
    
    WHERE Player = 'Auger-Aliassime, Felix'
    """
)

In [43]:
pd.read_sql(
    """
    SELECT Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins
    FROM mens_tennis
    WHERE Player = 'Zverev, Alexander'
    """
    ,
    con
)

,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Fr_QF_Appears,Fr_QF_Wins,Fr_SF_Wins,Fr_F_Wins
0,"Zverev, Alexander",15,9,3,0,7,4,1,0

In [44]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 16,
    QF_Wins = 10,
    SF_Wins = 4,
    F_Wins = 1,
    Fr_QF_Appears = 8,
    Fr_QF_Wins = 5,
    Fr_SF_Wins = 2,
    Fr_F_Wins = 1
    
    WHERE Player = 'Zverev, Alexander'
    """
)

In [45]:
con.commit()

In [46]:
pd.read_sql(
    """
    SELECT MIN(Player), MAX(Player)
    FROM mens_tennis
    """
    ,
    con
)

      MIN(Player)     MAX(Player)
0  Acuna, Ricardo  Zverev, Mischa

In [47]:
pd.read_sql(
    """
    SELECT Player, F_Wins, SF_Wins, QF_Wins, QF_Appears
    FROM mens_tennis
    WHERE F_Wins >= 1
    ORDER BY F_Wins DESC, SF_Wins DESC, QF_Wins DESC, QF_Appears DESC, Player
    """
    ,
    con
)

                    Player  F_Wins  SF_Wins  QF_Wins  QF_Appears
0          Djokovic, Novak      24       38       54          65
1            Nadal, Rafael      22       30       38          47
2           Federer, Roger      20       31       46          58
3            Sampras, Pete      14       18       23          29
4              Borg, Bjorn      11       16       17          21
5              Lendl, Ivan       8       19       28          34
6           Connors, Jimmy       8       15       31          41
7            Agassi, Andre       8       15       26          36
8            McEnroe, John       7       11       19          26
9           Wilander, Mats       7       11       14          20
10          Edberg, Stefan       6       11       19          26
11           Becker, Boris       6       10       18          23
12         Alcaraz, Carlos       6        8        9          13
13          Newcombe, John       5        7       10          18
14              Laver, Rod       5        6        6           7
15           Rosewall, Ken       4        8       13          15
16        Vilas, Guillermo       4        8       12          19
17            Courier, Jim       4        7       11          15
18          Sinner, Jannik       4        6        9          14
19            Murray, Andy       3       11       21          30
20            Ashe, Arthur       3        5       10          15
21              Kodes, Jan       3        5        6          10
22          Wawrinka, Stan       3        4        9          18
23        Kuerten, Gustavo       3        3        3           8
24           Nastase, Ilie       2        5        6          12
25         Hewitt, Lleyton       2        4        8          15
26            Safin, Marat       2        4        7           9
27         Rafter, Patrick       2        4        7           7
28     Kafelnikov, Yevgeny       2        3        6          13
29             Smith, Stan       2        3        5          10
30         Bruguera, Sergi       2        3        4           4
31            Kriek, Johan       2        2        5          11
32        Medvedev, Daniil       1        6        9          10
33           Roddick, Andy       1        5       10          19
34       Zverev, Alexander       1        4       10          16
35          Chang, Michael       1        4        8          13
36       Ivanisevic, Goran       1        4        7          14
37          Thiem, Dominic       1        4        6           8
38       Gerulaitis, Vitas       1        3        8          11
39            Cilic, Marin       1        3        6          14
40          Stich, Michael       1        3        6          10
41    Ferrero, Juan Carlos       1        3        6           9
42               Cash, Pat       1        3        5           9
43  Del Potro, Juan Martin       1        2        6          13
44          Tanner, Roscoe       1        2        6          11
45         Orantes, Manuel       1        2        4           9
46          Gimeno, Andres       1        2        4           5
47            Moya, Carlos       1        2        3           8
48             Korda, Petr       1        2        2           6
49       Krajicek, Richard       1        1        4           9
50          Muster, Thomas       1        1        4           9
51        Panatta, Adriano       1        1        3           6
52         Edmondson, Mark       1        1        3           5
53           Noah, Yannick       1        1        2          10
54           Costa, Albert       1        1        2           5
55       Johansson, Thomas       1        1        2           4
56           Gomez, Andres       1        1        1           6
57          Teacher, Brian       1        1        1           3
58          Gaudio, Gaston       1        1        1           1

In [50]:
pd.read_sql(
    """
    SELECT Player, QF_Appears, SF_Wins
    FROM mens_tennis
    WHERE QF_Appears >= 10
    ORDER BY QF_Appears DESC, Player
    """
    ,
    con
)

                    Player  QF_Appears  SF_Wins
0          Djokovic, Novak          65       38
1           Federer, Roger          58       31
2            Nadal, Rafael          47       30
3           Connors, Jimmy          41       15
4            Agassi, Andre          36       15
5              Lendl, Ivan          34       19
6             Murray, Andy          30       11
7            Sampras, Pete          29       18
8           Edberg, Stefan          26       11
9            McEnroe, John          26       11
10           Becker, Boris          23       10
11             Borg, Bjorn          21       16
12          Wilander, Mats          20       11
13           Roddick, Andy          19        5
14        Vilas, Guillermo          19        8
15          Newcombe, John          18        7
16          Wawrinka, Stan          18        4
17          Berdych, Tomas          17        1
18           Ferrer, David          17        1
19       Zverev, Alexander          16        4
20            Ashe, Arthur          15        5
21            Courier, Jim          15        7
22         Hewitt, Lleyton          15        4
23           Rosewall, Ken          15        8
24     Tsonga, Jo-Wilfried          15        1
25            Cilic, Marin          14        3
26       Ivanisevic, Goran          14        4
27          Sinner, Jannik          14        6
28         Alcaraz, Carlos          13        8
29          Chang, Michael          13        4
30  Del Potro, Juan Martin          13        2
31     Kafelnikov, Yevgeny          13        3
32           Nastase, Ilie          12        5
33          Nishikori, Kei          12        1
34             Roche, Tony          12        3
35       Gerulaitis, Vitas          11        3
36            Kriek, Johan          11        2
37              Okker, Tom          11        1
38          Tanner, Roscoe          11        2
39      Davydenko, Nikolay          10        0
40             Henman, Tim          10        0
41              Kodes, Jan          10        5
42            Martin, Todd          10        2
43        Medvedev, Daniil          10        6
44           Monfils, Gael          10        0
45       Nalbandian, David          10        1
46           Noah, Yannick          10        1
47           Raonic, Milos          10        1
48          Rublev, Andrey          10        0
49             Smith, Stan          10        3
50          Stich, Michael          10        3

In [51]:
con.close()

In [54]:
con = sqlite3.connect('../data/tennis.db')

In [55]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Alcaraz, Carlos'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,365,"Alcaraz, Carlos",13,9,8,6,2,0,0,0,...,2,2,3,3,3,2,4,3,2,2

Not sure why Alcaraz's record reverted back to his 2025 totals. I went back and ran the Alcaraz update cell for the 2026 Australian Open.

In [58]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Alcaraz, Carlos'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,365,"Alcaraz, Carlos",14,10,9,7,3,1,1,1,...,2,2,3,3,3,2,4,3,2,2

In [62]:
con.commit()

OperationalError: database is locked

In [64]:
cursor = con.cursor()

In [65]:
cursor.close()

In [66]:
con.commit()

OperationalError: database is locked

In [67]:
con.close()

In [3]:
con = sqlite3.connect('../data/tennis.db')

In [6]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    
    WHERE F_Wins = 0
    ORDER BY SF_Wins DESC, QF_Wins DESC, QF_Appears DESC
    
    LIMIT 20
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,55,"Roche, Tony",12,8,3,0,5,2,0,0,...,0,0,4,3,1,0,2,2,2,0
1,368,"Ruud, Casper",4,4,3,0,0,0,0,0,...,2,0,0,0,0,0,1,1,1,0
2,56,"Martin, Todd",10,6,2,0,3,1,1,0,...,0,0,4,2,0,0,3,3,1,0
3,73,"Tsitsipas, Stefanos",8,6,2,0,4,4,1,0,...,1,0,0,0,0,0,0,0,0,0
4,57,"Pioline, Cedric",8,4,2,0,0,0,0,0,...,0,0,4,1,1,0,2,2,1,0
5,58,"Mecir, Miloslav",7,4,2,0,2,1,1,0,...,0,0,2,1,0,0,2,1,1,0
6,59,"Corretja, Alex",6,3,2,0,0,0,0,0,...,2,0,0,0,0,0,1,0,0,0
7,60,"Curren, Kevin",4,3,2,0,1,1,1,0,...,0,0,3,2,1,0,0,0,0,0
8,62,"Soderling, Robin",6,2,2,0,0,0,0,0,...,2,0,1,0,0,0,2,0,0,0
9,63,"Philippoussis, Mark",5,2,2,0,0,0,0,0,...,0,0,4,1,1,0,1,1,1,0
10,64,"Anderson, Kevin",3,2,2,0,0,0,0,0,...,0,0,1,1,1,0,2,1,1,0
11,65,"Denton, Steve",2,2,2,0,2,2,2,0,...,0,0,0,0,0,0,0,0,0,0
12,66,"Berdych, Tomas",17,7,1,0,7,2,0,0,...,0,0,5,3,1,0,2,1,0,0
13,67,"Ferrer, David",17,6,1,0,6,2,0,0,...,1,0,2,0,0,0,3,2,0,0
14,68,"Tsonga, Jo-Wilfried",15,6,1,0,5,2,1,0,...,0,0,4,2,0,0,3,0,0,0
15,69,"Okker, Tom",11,5,1,0,2,1,0,0,...,0,0,5,1,0,0,2,2,1,0
16,70,"Nalbandian, David",10,5,1,0,4,1,0,0,...,0,0,2,1,1,0,2,1,0,0
17,71,"Leconte, Henri",9,4,1,0,0,0,0,0,...,1,0,3,1,0,0,1,0,0,0
18,72,"Solomon, Harold",6,4,1,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
19,74,"Nishikori, Kei",12,3,1,0,4,0,0,0,...,0,0,2,0,0,0,3,3,1,0

In [7]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    
    WHERE F_Wins = 0
    ORDER BY QF_Wins DESC, QF_Appears DESC
    
    LIMIT 20
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,55,"Roche, Tony",12,8,3,0,5,2,0,0,...,0,0,4,3,1,0,2,2,2,0
1,66,"Berdych, Tomas",17,7,1,0,7,2,0,0,...,0,0,5,3,1,0,2,1,0,0
2,67,"Ferrer, David",17,6,1,0,6,2,0,0,...,1,0,2,0,0,0,3,2,0,0
3,68,"Tsonga, Jo-Wilfried",15,6,1,0,5,2,1,0,...,0,0,4,2,0,0,3,0,0,0
4,56,"Martin, Todd",10,6,2,0,3,1,1,0,...,0,0,4,2,0,0,3,3,1,0
5,107,"Henman, Tim",10,6,0,0,0,0,0,0,...,0,0,8,4,0,0,1,1,0,0
6,73,"Tsitsipas, Stefanos",8,6,2,0,4,4,1,0,...,1,0,0,0,0,0,0,0,0,0
7,69,"Okker, Tom",11,5,1,0,2,1,0,0,...,0,0,5,1,0,0,2,2,1,0
8,70,"Nalbandian, David",10,5,1,0,4,1,0,0,...,0,0,2,1,1,0,2,1,0,0
9,108,"Davydenko, Nikolay",10,4,0,0,4,0,0,0,...,0,0,0,0,0,0,2,2,0,0
10,71,"Leconte, Henri",9,4,1,0,0,0,0,0,...,1,0,3,1,0,0,1,0,0,0
11,109,"Grosjean, Sebastien",9,4,0,0,4,1,0,0,...,0,0,3,2,0,0,0,0,0,0
12,57,"Pioline, Cedric",8,4,2,0,0,0,0,0,...,0,0,4,1,1,0,2,2,1,0
13,110,"Haas, Tommy",8,4,0,0,3,3,0,0,...,0,0,1,1,0,0,3,0,0,0
14,58,"Mecir, Miloslav",7,4,2,0,2,1,1,0,...,0,0,2,1,0,0,2,1,1,0
15,72,"Solomon, Harold",6,4,1,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
16,368,"Ruud, Casper",4,4,3,0,0,0,0,0,...,2,0,0,0,0,0,1,1,1,0
17,74,"Nishikori, Kei",12,3,1,0,4,0,0,0,...,0,0,2,0,0,0,3,3,1,0
18,75,"Raonic, Milos",10,3,1,0,5,1,0,0,...,0,0,4,2,1,0,0,0,0,0
19,111,"Ramirez, Raul",9,3,0,0,0,0,0,0,...,0,0,3,1,0,0,1,0,0,0

In [9]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    
    WHERE Player = 'Dimitrov, Grigor'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,112,"Dimitrov, Grigor",8,3,0,0,4,1,0,0,...,0,0,1,1,0,0,2,1,0,0

## 2026 Wimbledon

In [ ]:
# QFs
# Sinner d. Struff
# Djokovic d. Auger-Aliassime
# Fery d. Cobolli
# Zverev d. Fritz

# SFs
# Sinner d. Djokovic
# Zverev d. Fery

# Fs
# Sinner d. Zverev

In [2]:
import sys
sys.path.append('..')

In [26]:
from src.slam_update import update_db

In [7]:
con = sqlite3.connect('../data/tennis.db')

In [13]:
pd.read_sql(
    """
    SELECT Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Wim_QF_Appears, Wim_QF_Wins, Wim_SF_Wins, Wim_F_Wins
    FROM mens_tennis
    WHERE Player = 'Sinner, Jannik' OR Player = 'Zverev, Alexander' OR Player = 'Djokovic, Novak'\
    OR Player = 'Auger-Aliassime, Felix' OR Player = 'Cobolli, Flavio' OR Player = 'Fritz, Taylor'
    ORDER BY Player
    """
    ,
    con
)

,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins
0,"Auger-Aliassime, Felix",5,2,0,0,1,0,0,0
1,"Cobolli, Flavio",2,1,1,0,1,0,0,0
2,"Djokovic, Novak",65,54,38,24,16,14,10,7
3,"Fritz, Taylor",7,2,1,0,3,1,0,0
4,"Sinner, Jannik",14,9,6,4,4,2,1,1
5,"Zverev, Alexander",16,10,4,1,0,0,0,0

In [33]:
## I tried using the function here but ran into a series of errors, even after
## copying the body of the function into the notebok.

In [34]:
update_db(champ="Sinner, Jannik", runner_up="Zverev, Alexander", losing_sfs=["Djokovic, Novak", "Fery, Arthur"],
         losing_qfs=["Struff, Jan-Lennard", "Auger-Aliassime, Felix", "Cobolli, Flavio", "Fritz, Taylor"],
         which_slam='wim')

OperationalError: near "WHERE": syntax error

In [28]:
con = sqlite3.connect('../data/tennis.db')

In [35]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 15,
    QF_Wins = 10,
    SF_Wins = 7,
    F_Wins = 5,
    Wim_QF_Appears = 5,
    Wim_QF_Wins = 3,
    Wim_SF_Wins = 2,
    Wim_F_Wins = 2
    
    WHERE Player = 'Sinner, Jannik'
    """
)

In [36]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (389, 'Struff, Jan-Lennard', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0)
    """
)

In [37]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 66,
    QF_Wins = 55,
    Wim_QF_Appears = 17,
    Wim_QF_Wins = 15
    
    WHERE Player = 'Djokovic, Novak'
    """
)

In [38]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 6,
    Wim_QF_Appears = 2
    
    WHERE Player = 'Auger-Aliassime, Felix'
    """
)

In [39]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (390, 'Fery, Arthur', 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 1, 0, 0, 0, 0, 0, 0)
    """
)

In [40]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 3,
    Wim_QF_Appears = 2
    
    WHERE Player = 'Cobolli, Flavio'
    """
)

In [41]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 17,
    QF_Wins = 11,
    SF_Wins = 5,
    Wim_QF_Appears = 1,
    Wim_QF_Wins = 1,
    Wim_SF_Wins = 1
    
    WHERE Player = 'Zverev, Alexander'
    """
)

In [42]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 8,
    Wim_QF_Appears = 4
    
    WHERE Player = 'Fritz, Taylor'
    """
)

In [43]:
con.commit()

In [46]:
pd.read_sql(
    """
    SELECT Player, F_Wins, SF_Wins, QF_Wins, QF_Appears
    FROM mens_tennis
    WHERE F_Wins >= 1
    ORDER BY F_Wins DESC, SF_Wins DESC, QF_Wins DESC, QF_Appears DESC, Player
    """
    ,
    con
)

                    Player  F_Wins  SF_Wins  QF_Wins  QF_Appears
0          Djokovic, Novak      24       38       55          66
1            Nadal, Rafael      22       30       38          47
2           Federer, Roger      20       31       46          58
3            Sampras, Pete      14       18       23          29
4              Borg, Bjorn      11       16       17          21
5              Lendl, Ivan       8       19       28          34
6           Connors, Jimmy       8       15       31          41
7            Agassi, Andre       8       15       26          36
8            McEnroe, John       7       11       19          26
9           Wilander, Mats       7       11       14          20
10         Alcaraz, Carlos       7        9       10          14
11          Edberg, Stefan       6       11       19          26
12           Becker, Boris       6       10       18          23
13          Newcombe, John       5        7       10          18
14          Sinner, Jannik       5        7       10          15
15              Laver, Rod       5        6        6           7
16           Rosewall, Ken       4        8       13          15
17        Vilas, Guillermo       4        8       12          19
18            Courier, Jim       4        7       11          15
19            Murray, Andy       3       11       21          30
20            Ashe, Arthur       3        5       10          15
21              Kodes, Jan       3        5        6          10
22          Wawrinka, Stan       3        4        9          18
23        Kuerten, Gustavo       3        3        3           8
24           Nastase, Ilie       2        5        6          12
25         Hewitt, Lleyton       2        4        8          15
26            Safin, Marat       2        4        7           9
27         Rafter, Patrick       2        4        7           7
28     Kafelnikov, Yevgeny       2        3        6          13
29             Smith, Stan       2        3        5          10
30         Bruguera, Sergi       2        3        4           4
31            Kriek, Johan       2        2        5          11
32        Medvedev, Daniil       1        6        9          10
33       Zverev, Alexander       1        5       11          17
34           Roddick, Andy       1        5       10          19
35          Chang, Michael       1        4        8          13
36       Ivanisevic, Goran       1        4        7          14
37          Thiem, Dominic       1        4        6           8
38       Gerulaitis, Vitas       1        3        8          11
39            Cilic, Marin       1        3        6          14
40          Stich, Michael       1        3        6          10
41    Ferrero, Juan Carlos       1        3        6           9
42               Cash, Pat       1        3        5           9
43  Del Potro, Juan Martin       1        2        6          13
44          Tanner, Roscoe       1        2        6          11
45         Orantes, Manuel       1        2        4           9
46          Gimeno, Andres       1        2        4           5
47            Moya, Carlos       1        2        3           8
48             Korda, Petr       1        2        2           6
49       Krajicek, Richard       1        1        4           9
50          Muster, Thomas       1        1        4           9
51        Panatta, Adriano       1        1        3           6
52         Edmondson, Mark       1        1        3           5
53           Noah, Yannick       1        1        2          10
54           Costa, Albert       1        1        2           5
55       Johansson, Thomas       1        1        2           4
56           Gomez, Andres       1        1        1           6
57          Teacher, Brian       1        1        1           3
58          Gaudio, Gaston       1        1        1           1

In [47]:
con.commit()

In [48]:
con.close()

## 2026 US Open

In [1]:
# QFs
# Zverev d. Van de Zandschulp
# Khachanov d. Blockx
# Tiafoe d. Michelsen
# Shelton d. Alcaraz

# SFs
# Zverev d. Khachanov
# Shelton d. Tiafoe

# Fs
# Zverev d. Shelton

In [4]:
con = sqlite3.connect('../data/tennis.db')

In [5]:
pd.read_sql(
    """
    SELECT QF_Appears, QF_Wins, SF_Wins, F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins
    FROM mens_tennis
    WHERE Player = 'Zverev, Alexander'
    """
    ,
    con
)

,QF_Appears,QF_Wins,SF_Wins,F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,17,11,5,1,4,2,1,0

In [6]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 18,
    QF_Wins = 12,
    SF_Wins = 6,
    F_Wins = 2,
    US_QF_Appears = 5,
    US_QF_Wins = 3,
    US_SF_Wins = 2,
    US_F_Wins = 1
    
    WHERE Player = 'Zverev, Alexander'
    """
)

In [8]:
pd.read_sql(
    """
    SELECT QF_Appears, QF_Wins, SF_Wins, F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins
    FROM mens_tennis
    WHERE Player = 'Van de Zandschulp, Botic'
    """
    ,
    con
)

,QF_Appears,QF_Wins,SF_Wins,F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,1,0,0,0,1,0,0,0

In [9]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 2,
    US_QF_Appears = 2
    
    WHERE Player = 'Van de Zandschulp, Botic'
    """
)

In [10]:
pd.read_sql(
    """
    SELECT QF_Appears, QF_Wins, SF_Wins, F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins
    FROM mens_tennis
    WHERE Player = 'Khachanov, Karen'
    """
    ,
    con
)

,QF_Appears,QF_Wins,SF_Wins,F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,6,2,0,0,1,1,0,0

In [11]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 7,
    QF_Wins = 3,
    US_QF_Appears = 2,
    US_QF_Wins = 2
    
    WHERE Player = 'Khachanov, Karen'
    """
)

In [12]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (391, 'Blockx, Alexander', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0)
    """
)

In [13]:
pd.read_sql(
    """
    SELECT QF_Appears, QF_Wins, SF_Wins, F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins
    FROM mens_tennis
    WHERE Player = 'Tiafoe, Frances'
    """
    ,
    con
)

,QF_Appears,QF_Wins,SF_Wins,F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,5,2,0,0,3,2,0,0

In [14]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 6,
    QF_Wins = 3,
    US_QF_Appears = 4,
    US_QF_Appears = 3
    
    WHERE Player = 'Tiafoe, Frances'
    """
)

In [15]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (392, 'Michelsen, Alex', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0)
    """
)

In [16]:
pd.read_sql(
    """
    SELECT QF_Appears, QF_Wins, SF_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins
    FROM mens_tennis
    WHERE Player = 'Shelton, Ben'
    """
    ,
    con
)

   QF_Appears  QF_Wins  SF_Wins  US_QF_Appears  US_QF_Wins  US_SF_Wins
0           5        2        0              1           1           0

In [17]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 6,
    QF_Wins = 3,
    SF_Wins = 1,
    US_QF_Appears = 2,
    US_QF_Wins = 2,
    US_SF_Wins = 1
    
    WHERE Player = 'Shelton, Ben'
    """
)

In [18]:
pd.read_sql(
    """
    SELECT QF_Appears, US_QF_Appears
    FROM mens_tennis
    WHERE Player = 'Alcaraz, Carlos'
    """
    ,
    con
)

   QF_Appears  US_QF_Appears
0          14              4

In [19]:
con.execute(
    """
    UPDATE mens_tennis
    
    SET QF_Appears = 15,
    US_QF_Appears = 5
    
    WHERE Player = 'Alcaraz, Carlos'
    """
)

In [20]:
con.commit()

In [22]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE F_Wins >= 1
    ORDER BY F_Wins DESC, SF_Wins DESC, QF_Wins DESC, QF_Appears DESC, Player
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,2,"Djokovic, Novak",66,55,38,24,16,13,11,10,...,7,3,17,15,10,7,14,14,10,4
1,1,"Nadal, Rafael",47,38,30,22,14,7,6,2,...,14,14,8,8,5,2,9,8,5,4
2,0,"Federer, Roger",58,46,31,20,15,15,7,6,...,5,1,18,13,12,8,13,10,7,5
3,3,"Sampras, Pete",29,23,18,14,6,5,3,2,...,0,0,9,8,7,7,10,9,8,5
4,4,"Borg, Bjorn",21,17,16,11,0,0,0,0,...,6,6,8,6,6,5,6,5,4,0
5,5,"Lendl, Ivan",34,28,19,8,8,7,4,2,...,5,3,7,7,2,0,12,9,8,3
6,6,"Connors, Jimmy",41,31,15,8,2,2,2,1,...,0,0,14,11,6,2,17,14,7,5
7,7,"Agassi, Andre",36,26,15,8,7,6,4,4,...,3,1,7,5,2,1,13,10,6,2
8,8,"McEnroe, John",26,19,11,7,4,1,0,0,...,1,0,9,8,5,3,9,8,5,4
9,9,"Wilander, Mats",20,14,11,7,5,5,4,3,...,5,3,3,0,0,0,5,3,2,1
10,365,"Alcaraz, Carlos",15,10,9,7,3,1,1,1,...,2,2,3,3,3,2,5,3,2,2
11,10,"Edberg, Stefan",26,19,11,6,10,8,5,2,...,1,0,7,6,3,2,5,4,2,2
12,11,"Becker, Boris",23,18,10,6,4,2,2,2,...,0,0,11,9,7,3,4,4,1,1
13,12,"Newcombe, John",18,10,7,5,8,3,3,2,...,0,0,4,3,3,2,5,4,1,1
14,343,"Sinner, Jannik",15,10,7,5,4,3,2,2,...,1,0,5,3,2,2,3,2,2,1
15,13,"Laver, Rod",7,6,6,5,1,1,1,1,...,2,1,3,2,2,2,1,1,1,1
16,14,"Rosewall, Ken",15,13,8,4,5,4,2,2,...,2,1,3,3,2,0,5,4,2,1
17,15,"Vilas, Guillermo",19,12,8,4,4,4,3,2,...,4,1,2,0,0,0,4,4,1,1
18,16,"Courier, Jim",15,11,7,4,5,3,2,2,...,3,2,2,1,1,0,3,3,1,0
19,17,"Murray, Andy",30,21,11,3,7,6,5,0,...,1,0,10,7,3,2,6,3,2,1
20,18,"Ashe, Arthur",15,10,5,3,4,3,2,1,...,0,0,3,3,1,1,6,4,2,1
21,19,"Kodes, Jan",10,6,5,3,0,0,0,0,...,2,2,3,2,1,1,3,2,2,0
22,20,"Wawrinka, Stan",18,9,4,3,5,3,1,1,...,2,1,2,0,0,0,6,3,1,1
23,21,"Kuerten, Gustavo",8,3,3,3,0,0,0,0,...,3,3,1,0,0,0,2,0,0,0
24,77,"Zverev, Alexander",18,12,6,2,4,3,1,0,...,2,1,1,1,1,0,5,3,2,1
25,22,"Nastase, Ilie",12,6,5,2,0,0,0,0,...,2,1,4,2,2,0,3,2,1,1
26,23,"Hewitt, Lleyton",15,8,4,2,1,1,1,0,...,0,0,5,2,1,1,7,5,2,1
27,24,"Safin, Marat",9,7,4,2,3,3,3,1,...,0,0,2,1,0,0,2,2,1,1
28,25,"Rafter, Patrick",7,7,4,2,1,1,0,0,...,0,0,3,3,2,0,2,2,2,2
29,26,"Kafelnikov, Yevgeny",13,6,3,2,5,2,2,1,...,1,1,1,0,0,0,2,2,0,0
30,27,"Smith, Stan",10,5,3,2,0,0,0,0,...,0,0,3,3,2,1,5,2,1,1
31,28,"Bruguera, Sergi",4,4,3,2,0,0,0,0,...,3,2,0,0,0,0,0,0,0,0
32,29,"Kriek, Johan",11,5,2,2,5,3,2,2,...,0,0,2,0,0,0,3,1,0,0
33,61,"Medvedev, Daniil",10,9,6,1,3,3,3,0,...,0,0,2,2,0,0,4,4,3,1
34,30,"Roddick, Andy",19,10,5,1,6,4,0,0,...,0,0,5,4,3,0,8,2,2,1
35,31,"Chang, Michael",13,8,4,1,3,3,1,0,...,2,1,1,0,0,0,5,3,1,0
36,32,"Ivanisevic, Goran",14,7,4,1,3,0,0,0,...,0,0,7,6,4,1,1,1,0,0
37,33,"Thiem, Dominic",8,6,4,1,1,1,1,0,...,2,0,0,0,0,0,2,1,1,1
38,34,"Gerulaitis, Vitas",11,8,3,1,1,1,1,1,...,1,0,4,2,0,0,3,3,1,0
39,37,"Cilic, Marin",14,6,3,1,2,2,1,0,...,0,0,4,1,1,0,5,2,1,1
40,35,"Stich, Michael",10,6,3,1,2,1,0,0,...,1,0,4,2,1,1,2,1,1,0
41,36,"Ferrero, Juan Carlos",9,6,3,1,2,1,0,0,...,2,1,2,0,0,0,1,1,1,0
42,38,"Cash, Pat",9,5,3,1,4,2,2,0,...,0,0,4,2,1,1,1,1,0,0
43,39,"Del Potro, Juan Martin",13,6,2,1,2,0,0,0,...,0,0,2,1,0,0,6,3,2,1
44,40,"Tanner, Roscoe",11,6,2,1,1,1,1,1,...,0,0,5,3,1,0,5,2,0,0
45,41,"Orantes, Manuel",9,4,2,1,0,0,0,0,...,1,0,1,1,0,0,4,1,1,1
46,42,"Gimeno, Andres",5,4,2,1,1,1,1,0,...,1,1,1,1,0,0,0,0,0,0
47,43,"Moya, Carlos",8,3,2,1,2,1,1,0,...,1,1,0,0,0,0,2,1,0,0
48,44,"Korda, Petr",6,2,2,1,2,1,1,1,...,1,0,1,0,0,0,2,0,0,0
49,45,"Krajicek, Richard",9,4,1,1,1,1,0,0,...,0,0,3,2,1,1,3,0,0,0
50,46,"Muster, Thomas",9,4,1,1,3,2,0,0,...,1,1,0,0,0,0,3,0,0,0
51,47,"Panatta, Adriano",6,3,1,1,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
52,48,"Edmondson, Mark",5,3,1,1,4,2,1,1,...,0,0,1,1,0,0,0,0,0,0
53,49,"Noah, Yannick",10,2,1,1,2,1,0,0,...,1,1,0,0,0,0,3,0,0,0
54,50,"Costa, Albert",5,2,1,1,1,0,0,0,...,1,1,0,0,0,0,0,0,0,0
55,51,"Johansson, Thomas",4,2,1,1,1,1,1,1,...,0,0,1,1,0,0,2,0,0,0
56,52,"Gomez, Andres",6,1,1,1,0,0,0,0,...,1,1,1,0,0,0,1,0,0,0
57,53,"Teacher, Brian",3,1,1,1,2,1,1,1,...,0,0,1,0,0,0,0,0,0,0
58,54,"Gaudio, Gaston",1,1,1,1,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0

In [23]:
con.close()