In [21]:
import pandas as pd
import sys, os

## 2022 Season

In [1]:
import pandas as pd

In [69]:
df = pd.read_csv('../data/champ_droughts.csv')
copy = df.copy()

In [70]:
copy.drop('Unnamed: 0', axis=1).to_csv('../data/champ_droughts.csv', index=False)

In [74]:
df = pd.read_csv('../data/ws_droughts.csv')

In [75]:
df = pd.read_csv('../data/lcsp_droughts.csv')
copy = df.copy()
copy.drop('Unnamed: 0', axis=1).to_csv('../data/lcsp_droughts.csv', index=False)

In [76]:
df = pd.read_csv('../data/postseason_droughts.csv')
copy = df.copy()
copy.drop('Unnamed: 0', axis=1).to_csv('../data/postseason_droughts.csv', index=False)

In [77]:
post_teams_22 = ['Astros (15)', 'Blue Jays (8)', 'Braves (27)', 'Cardinals (31)', 'Indians (15)',
                 'Dodgers (35)', 'Mariners (4)', 'Mets (9)', 'Phillies (14)', 'Padres (6)',
                'Rays (7)', 'Yankees (57)']

In [78]:
lcsp_teams_22 = ['Padres (2)', 'Yankees (46)', 'Astros (9)', 'Phillies (11)']

In [79]:
ws_teams_22 = ['Astros (4)', 'Phillies (7)']

In [80]:
champ_team_22 = 'Astros (1)'

In [81]:
import sys, os

In [82]:
sys.path.append(os.pardir)

In [83]:
sys.path

['/Users/gadamico/Fun/Sports-Data/baseball/notebooks',
 '/Users/gadamico/opt/anaconda3/envs/learn-env/lib/python38.zip',
 '/Users/gadamico/opt/anaconda3/envs/learn-env/lib/python3.8',
 '/Users/gadamico/opt/anaconda3/envs/learn-env/lib/python3.8/lib-dynload',
 '',
 '/Users/gadamico/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages',
 '/Users/gadamico/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages/IPython/extensions',
 '/Users/gadamico/.ipython',
 '..',
 '..']

In [84]:
from src.update_mlb import *

In [85]:
update_table(post_teams=post_teams_22, lcsp_teams=lcsp_teams_22, ws_teams=ws_teams_22,
            champ_team=champ_team_22, new_year='2022')

In [87]:
pd.read_csv('../data/champ_droughts.csv')

,TEAM/YEAR,2022,2021,2020,2019,2018,2017,2016,2015,2014,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1903
0,Indians (2),1 (73),72*,71*,70*,69*,68*,67*,66,65,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
1,Rangers (0),2 (61),60,59,58,57,56,55,54,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Brewers (0),3 (53),52,51,50,49,48,47,46,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Padres (0),3 (53),52,51,50,49,48,47,46,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mariners (0),5 (45),44,43,42,41,40,39,38,37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Pirates (5),6 (42),41,40,39,38,37,36,35,34,...,4,3,2,1,0,5*,4*,3*,2*,1*
6,Orioles (3),7 (38),37,36,35,34,33,32,31,30,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
7,Tigers (4),8 (37),36,35,34,33,32,31,30,29,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
8,Mets (2),9 (35),34,33,32,31,30,29,28,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Athletics (9),10 (32),31,30,29,28,27,26,25,24,...,0,1,0,0,6*,5*,4*,3*,2*,1*
10,Reds (5),11 (31),30,29,28,27,26,25,24,23,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
11,Twins (3),12 (30),29,28,27,26,25,24,23,22,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
12,Rockies (0),13 (29),28,27,26,25,24,23,22,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Blue Jays (2),14 (28),27,26,25,24,23,22,21,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Rays (0),15 (25),24,23,22,21,20,19,18,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Diamondbacks (1),16 (21),20,19,18,17,16,15,14,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Angels (1),17 (20),19,18,17,16,15,14,13,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Marlins (2),18 (19),18,17,16,15,14,13,12,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,White Sox (3),19 (17),16,15,14,13,12,11,10,9,...,7,6,5,4,3,2,1,0,2*,1*
19,Phillies (2),20 (14),13,12,11,10,9,8,7,6,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
20,Yankees (27),21 (13),12,11,10,9,8,7,6,5,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
21,Cardinals (11),22 (11),10,9,8,7,6,5,4,3,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
22,Giants (8),23 (8),7,6,5,4,3,2,1,0,...,8,7,6,5,4,3,2,1,0,1*
23,Royals (2),24 (7),6,5,4,3,2,1,0,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Cubs (3),25 (6),5,4,3,2,1,0,106**,105*,...,5,4,3,2,1,0,0,3*,2*,1*
25,Red Sox (9),26 (4),3,2,1,0,4,3,2,1,...,1,0,7,6,5,4,3,2,1,0
26,Nationals (1),27 (3),2,1,0,49,48,47,46,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Dodgers (7),28 (2),1,0,30,29,28,27,26,25,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
28,Braves (4),29 (1),0,25,24,23,22,21,20,19,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
29,Astros (2),30 (0),4,3,2,1,0,54,53,52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2023 Season

In [88]:
post_teams_23 = ['Astros (16)', 'Blue Jays (9)', 'Braves (28)', 'Brewers (8)', 'Diamondbacks (6)',
                'Dodgers (36)', 'Marlins (3)', 'Orioles (14)', 'Phillies (15)', 'Rangers (8)',
                'Rays (8)', 'Twins (17)']
lcsp_teams_23 = ['Astros (10)', 'Diamondbacks (2)', 'Phillies (12)', 'Rangers (2)']
ws_teams_23 = ['Diamondbacks (1)', 'Rangers (2)']
champ_team_23 = 'Rangers (0)'

In [90]:
update_table(post_teams=post_teams_23, lcsp_teams=lcsp_teams_23, ws_teams=ws_teams_23,
             champ_team=champ_team_23, new_year='2023')

In [91]:
pd.read_csv('../data/champ_droughts.csv')

,TEAM/YEAR,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1903
0,Indians (2),1 (74),73*,72*,71*,70*,69*,68*,67*,66,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
1,Brewers (0),2 (54),53,52,51,50,49,48,47,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Padres (0),2 (54),53,52,51,50,49,48,47,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mariners (0),4 (46),45,44,43,42,41,40,39,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pirates (5),5 (43),42,41,40,39,38,37,36,35,...,4,3,2,1,0,5*,4*,3*,2*,1*
5,Orioles (3),6 (39),38,37,36,35,34,33,32,31,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
6,Tigers (4),7 (38),37,36,35,34,33,32,31,30,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
7,Mets (2),8 (36),35,34,33,32,31,30,29,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Athletics (9),9 (33),32,31,30,29,28,27,26,25,...,0,1,0,0,6*,5*,4*,3*,2*,1*
9,Reds (5),10 (32),31,30,29,28,27,26,25,24,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
10,Twins (3),11 (31),30,29,28,27,26,25,24,23,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
11,Rockies (0),12 (30),29,28,27,26,25,24,23,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Blue Jays (2),13 (29),28,27,26,25,24,23,22,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Rays (0),14 (26),25,24,23,22,21,20,19,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Diamondbacks (1),15 (22),21,20,19,18,17,16,15,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Angels (1),16 (21),20,19,18,17,16,15,14,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Marlins (2),17 (20),19,18,17,16,15,14,13,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,White Sox (3),18 (18),17,16,15,14,13,12,11,10,...,7,6,5,4,3,2,1,0,2*,1*
18,Phillies (2),19 (15),14,13,12,11,10,9,8,7,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
19,Yankees (27),20 (14),13,12,11,10,9,8,7,6,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
20,Cardinals (11),21 (12),11,10,9,8,7,6,5,4,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
21,Giants (8),22 (9),8,7,6,5,4,3,2,1,...,8,7,6,5,4,3,2,1,0,1*
22,Royals (2),23 (8),7,6,5,4,3,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Cubs (3),24 (7),6,5,4,3,2,1,0,106**,...,5,4,3,2,1,0,0,3*,2*,1*
24,Red Sox (9),25 (5),4,3,2,1,0,4,3,2,...,1,0,7,6,5,4,3,2,1,0
25,Nationals (1),26 (4),3,2,1,0,49,48,47,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Dodgers (7),27 (3),2,1,0,30,29,28,27,26,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
27,Braves (4),28 (2),1,0,25,24,23,22,21,20,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
28,Astros (2),29 (1),0,4,3,2,1,0,54,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Rangers (1),30 (0),61,60,59,58,57,56,55,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2024 Season

### Getting Current Numbers

In [2]:
pd.read_csv('../data/champ_droughts.csv')

,TEAM/YEAR,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1903
0,Indians (2),1 (74),73*,72*,71*,70*,69*,68*,67*,66,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
1,Brewers (0),2 (54),53,52,51,50,49,48,47,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Padres (0),2 (54),53,52,51,50,49,48,47,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mariners (0),4 (46),45,44,43,42,41,40,39,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pirates (5),5 (43),42,41,40,39,38,37,36,35,...,4,3,2,1,0,5*,4*,3*,2*,1*
5,Orioles (3),6 (39),38,37,36,35,34,33,32,31,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
6,Tigers (4),7 (38),37,36,35,34,33,32,31,30,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
7,Mets (2),8 (36),35,34,33,32,31,30,29,28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Athletics (9),9 (33),32,31,30,29,28,27,26,25,...,0,1,0,0,6*,5*,4*,3*,2*,1*
9,Reds (5),10 (32),31,30,29,28,27,26,25,24,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
10,Twins (3),11 (31),30,29,28,27,26,25,24,23,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
11,Rockies (0),12 (30),29,28,27,26,25,24,23,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Blue Jays (2),13 (29),28,27,26,25,24,23,22,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Rays (0),14 (26),25,24,23,22,21,20,19,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Diamondbacks (1),15 (22),21,20,19,18,17,16,15,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Angels (1),16 (21),20,19,18,17,16,15,14,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Marlins (2),17 (20),19,18,17,16,15,14,13,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,White Sox (3),18 (18),17,16,15,14,13,12,11,10,...,7,6,5,4,3,2,1,0,2*,1*
18,Phillies (2),19 (15),14,13,12,11,10,9,8,7,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
19,Yankees (27),20 (14),13,12,11,10,9,8,7,6,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
20,Cardinals (11),21 (12),11,10,9,8,7,6,5,4,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
21,Giants (8),22 (9),8,7,6,5,4,3,2,1,...,8,7,6,5,4,3,2,1,0,1*
22,Royals (2),23 (8),7,6,5,4,3,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Cubs (3),24 (7),6,5,4,3,2,1,0,106**,...,5,4,3,2,1,0,0,3*,2*,1*
24,Red Sox (9),25 (5),4,3,2,1,0,4,3,2,...,1,0,7,6,5,4,3,2,1,0
25,Nationals (1),26 (4),3,2,1,0,49,48,47,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Dodgers (7),27 (3),2,1,0,30,29,28,27,26,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
27,Braves (4),28 (2),1,0,25,24,23,22,21,20,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
28,Astros (2),29 (1),0,4,3,2,1,0,54,53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Rangers (1),30 (0),61,60,59,58,57,56,55,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
champ = pd.read_csv('../data/champ_droughts.csv')
champ['TEAM/YEAR'].replace('Indians (2)', 'Guardians (2)')
new_champ = champ.copy()
new_champ['TEAM/YEAR'] = champ['TEAM/YEAR'].replace('Indians (2)', 'Guardians (2)')
new_champ.to_csv('../data/champ_droughts.csv')

In [31]:
fixed_champ = pd.read_csv('../data/champ_droughts.csv')
fixed_champ = fixed_champ.drop('Unnamed: 0', axis=1)
fixed_champ.to_csv('../data/champ_droughts.csv', index=False)

In [3]:
pd.read_csv('../data/ws_droughts.csv')

,TEAM/YEAR,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1903
0,Mariners (0),1 (46),45*,44*,43*,42*,41,40,39,38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Pirates (7),2 (43),42,41,40,39,38,37,36,35,...,4,3,2,1,0,4,3,2,1,0
2,Brewers (1),3 (40),39,38,37,36,35,34,33,32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Orioles (7),4 (39),38,37,36,35,34,33,32,31,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
4,Athletics (14),5 (32),31,30,29,28,27,26,25,24,...,0,1,0,0,4,3,2,1,0,1*
5,Reds (9),5 (32),31,30,29,28,27,26,25,24,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
6,Twins (6),7 (31),30,29,28,27,26,25,24,23,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
7,Blue Jays (2),8 (29),28,27,26,25,24,23,22,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Padres (2),9 (25),24,23,22,21,20,19,18,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Angels (1),10 (21),20,19,18,17,16,15,14,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Marlins (2),11 (20),19,18,17,16,15,14,13,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,White Sox (5),12 (18),17,16,15,14,13,12,11,10,...,7,6,5,4,3,2,1,0,2*,1*
12,Rockies (1),13 (16),15,14,13,12,11,10,9,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Yankees (40),14 (14),13,12,11,10,9,8,7,6,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
14,Tigers (11),15 (11),10,9,8,7,6,5,4,3,...,4,3,2,1,0,0,0,3*,2*,1*
15,Cardinals (19),16 (10),9,8,7,6,5,4,3,2,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
16,Giants (20),17 (9),8,7,6,5,4,3,2,1,...,0,0,0,5,4,3,2,1,0,1*
17,Mets (5),18 (8),7,6,5,4,3,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Royals (4),18 (8),7,6,5,4,3,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Cubs (11),20 (7),6,5,4,3,2,1,0,69**,...,3,2,1,0,1,0,0,0,2*,1*
20,Indians (6),20 (7),6,5,4,3,2,1,0,18,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
21,Red Sox (13),22 (5),4,3,2,1,0,4,3,2,...,1,0,7,6,5,4,3,2,1,0
22,Nationals (1),23 (4),3,2,1,0,49*,48*,47*,46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Dodgers (21),24 (3),2,1,0,1,0,0,27,26,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
24,Rays (2),24 (3),2,1,0,11,10,9,8,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Braves (10),26 (2),1,0,21,20,19,18,17,16,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
26,Astros (5),27 (1),0,0,1,0,1,0,11,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Phillies (8),27 (1),0,12,11,10,9,8,7,6,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
28,Diamondbacks (2),29 (0),21,20,19,18,17,16,15,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Rangers (3),29 (0),11,10,9,8,7,6,5,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
ws = pd.read_csv('../data/ws_droughts.csv')
new_ws = ws.copy()
new_ws['TEAM/YEAR'] = ws['TEAM/YEAR'].replace('Indians (6)', 'Guardians (6)')
new_ws.to_csv('../data/ws_droughts.csv')

In [33]:
fixed_ws = pd.read_csv('../data/ws_droughts.csv')
fixed_ws = fixed_ws.drop('Unnamed: 0', axis=1)
fixed_ws.to_csv('../data/ws_droughts.csv', index=False)

In [4]:
pd.read_csv('../data/lcsp_droughts.csv')

,TEAM/YEAR,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1903
0,Pirates (14),1 (30),29*,28*,27*,26*,25,24,23,22,...,4,3,7,6,5,4,3,2,1,0
1,Reds (12),2 (28),27,26,25,24,23,22,21,20,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
2,Mariners (3),3 (22),21,20,19,18,17,16,15,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Twins (9),4 (21),20,19,18,17,16,15,14,13,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
4,Marlins (2),5 (20),19,18,17,16,15,14,13,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,White Sox (7),6 (18),17,16,15,14,13,12,11,10,...,7,6,5,4,3,2,1,0,2*,1*
6,Athletics (19),7 (17),16,15,14,13,12,11,10,9,...,0,1,0,0,4,3,2,1,0,1*
7,Rockies (1),8 (16),15,14,13,12,11,10,9,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Angels (6),9 (14),13,12,11,10,9,8,7,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Tigers (15),10 (10),9,8,7,6,5,4,3,2,...,4,3,2,1,0,0,0,3*,2*,1*
10,Giants (22),11 (9),8,7,6,5,4,3,2,1,...,0,0,0,5,4,3,2,1,0,1*
11,Orioles (12),11 (9),8,7,6,5,4,3,2,1,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
12,Mets (8),13 (8),7,6,5,4,3,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Royals (8),13 (8),7,6,5,4,3,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Blue Jays (7),15 (7),6,5,4,3,2,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Indians (8),15 (7),6,5,4,3,2,1,0,8,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
16,Cubs (16),17 (6),5,4,3,2,1,0,0,0,...,3,2,1,0,1,0,0,0,2*,1*
17,Brewers (3),18 (5),4,3,2,1,0,6,5,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Cardinals (26),19 (4),3,2,1,0,4,3,2,1,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
19,Nationals (2),19 (4),3,2,1,0,36*,35*,34*,33*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Rays (2),21 (3),2,1,0,11,10,9,8,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Braves (17),22 (2),1,0,0,18,17,16,15,14,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
22,Dodgers (28),22 (2),1,0,0,1,0,0,0,2,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
23,Red Sox (19),22 (2),1,0,2,1,0,4,3,2,...,1,0,7,6,5,4,3,2,1,0
24,Padres (3),25 (1),0,23,22,21,20,19,18,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Yankees (47),25 (1),0,2,1,0,1,0,4,3,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
26,Astros (11),27 (0),0,0,0,0,0,0,11,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Diamondbacks (3),27 (0),15,14,13,12,11,10,9,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Phillies (13),27 (0),0,11,10,9,8,7,6,5,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
29,Rangers (3),27 (0),11,10,9,8,7,6,5,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
lcsp = pd.read_csv('../data/lcsp_droughts.csv')
new_lcsp = lcsp.copy()
new_lcsp['TEAM/YEAR'] = lcsp['TEAM/YEAR'].replace('Indians (8)', 'Guardians (8)')
new_lcsp.to_csv('../data/lcsp_droughts.csv')

In [34]:
fixed_lcsp = pd.read_csv('../data/lcsp_droughts.csv')
fixed_lcsp = fixed_lcsp.drop('Unnamed: 0', axis=1)
fixed_lcsp.to_csv('../data/lcsp_droughts.csv', index=False)

In [5]:
pd.read_csv('../data/postseason_droughts.csv')

,TEAM/YEAR,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1903
0,Angels (10),1 (9),8*,7*,6,5,4,3,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tigers (16),1 (9),8,7,6,5,4,3,2,1,...,4,3,2,1,0,0,0,3*,2*,1*
2,Pirates (17),3 (8),7,6,5,4,3,2,1,0,...,4,3,2,1,0,4,3,2,1,0
3,Royals (9),3 (8),7,6,5,4,3,2,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Rockies (5),5 (5),4,3,2,1,0,0,7,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Nationals (6),6 (4),3,2,1,0,1,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Athletics (29),7 (3),2,1,0,0,0,3,2,1,...,0,1,0,0,4,3,2,1,0,1*
7,Cubs (21),7 (3),2,1,0,1,0,0,0,0,...,3,2,1,0,1,0,0,0,2*,1*
8,Reds (16),7 (3),2,1,0,6,5,4,3,2,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
9,Giants (27),10 (2),1,0,4,3,2,1,0,1,...,0,0,0,5,4,3,2,1,0,1*
10,Red Sox (25),10 (2),1,0,2,1,0,0,0,2,...,1,0,7,6,5,4,3,2,1,0
11,White Sox (11),10 (2),1,0,0,11,10,9,8,7,...,7,6,5,4,3,2,1,0,2*,1*
12,Cardinals (32),13 (1),0,0,0,0,3,2,1,0,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
13,Indians (16),13 (1),0,1,0,1,0,0,0,2,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
14,Mariners (5),13 (1),0,20,19*,18*,17*,16*,15*,14*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Mets (10),13 (1),0,5,4,3,2,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Padres (7),13 (1),0,1,0,13,12,11,10,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Yankees (58),13 (1),0,0,0,0,0,0,1,0,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
18,Astros (17),19 (0),0,0,0,0,0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Blue Jays (10),19 (0),0,1,0,3,2,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Braves (29),19 (0),0,0,0,0,0,4,3,2,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
21,Brewers (9),19 (0),1,0,0,0,0,6,5,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Diamondbacks (7),19 (0),5,4,3,2,1,0,5,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Dodgers (37),19 (0),0,0,0,0,0,0,0,0,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
24,Marlins (4),19 (0),2,1,0,16,15,14,13,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Orioles (15),19 (0),6,5,4,3,2,1,0,1,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
26,Phillies (16),19 (0),0,10,9,8,7,6,5,4,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
27,Rangers (9),19 (0),6,5,4,3,2,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Rays (9),19 (0),0,0,0,0,5,4,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Twins (18),19 (0),2,1,0,0,1,0,6,5,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*

In [14]:
ps = pd.read_csv('../data/postseason_droughts.csv')
new_ps = ps.copy()
new_ps['TEAM/YEAR'] = ps['TEAM/YEAR'].replace('Indians (16)', 'Guardians (16)')
new_ps.to_csv('../data/postseason_droughts.csv')

In [35]:
fixed_ps = pd.read_csv('../data/postseason_droughts.csv')
fixed_ps = fixed_ps.drop('Unnamed: 0', axis=1)
fixed_ps.to_csv('../data/postseason_droughts.csv', index=False)

In [15]:
post_teams_24 = ['Astros (17)', 'Braves (29)', 'Brewers (9)', 'Dodgers (37)', 'Guardians (16)', 'Mets (10)',
                 'Orioles (15)', 'Padres (7)', 'Phillies (16)', 'Royals (9)', 'Tigers (16)', 'Yankees (58)']

In [16]:
lcsp_teams_24 = [
    'Dodgers (28)', 'Guardians (8)', 'Mets (8)', 'Yankees (47)'
]

In [17]:
ws_teams_24 = [
    'Dodgers (21)', 'Yankees (40)'
]

In [18]:
champ_team_24 = 'Dodgers (7)'

In [22]:
sys.path.append(os.pardir)

In [23]:
from src.update_mlb import *

In [37]:
update_table(post_teams=post_teams_24, lcsp_teams=lcsp_teams_24, ws_teams=ws_teams_24,
             champ_team=champ_team_24, new_year='2024')

In [38]:
pd.read_csv('../data/champ_droughts.csv')

,TEAM/YEAR,2024,2023,2022,2021,2020,2019,2018,2017,2016,...,1913,1912,1911,1910,1909,1908,1907,1906,1905,1903
0,Guardians (2),1 (75),74*,73*,72*,71*,70*,69*,68*,67*,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
1,Brewers (0),2 (55),54,53,52,51,50,49,48,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Padres (0),2 (55),54,53,52,51,50,49,48,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mariners (0),4 (47),46,45,44,43,42,41,40,39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pirates (5),5 (44),43,42,41,40,39,38,37,36,...,4,3,2,1,0,5*,4*,3*,2*,1*
5,Orioles (3),6 (40),39,38,37,36,35,34,33,32,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
6,Tigers (4),7 (39),38,37,36,35,34,33,32,31,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
7,Mets (2),8 (37),36,35,34,33,32,31,30,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Athletics (9),9 (34),33,32,31,30,29,28,27,26,...,0,1,0,0,6*,5*,4*,3*,2*,1*
9,Reds (5),10 (33),32,31,30,29,28,27,26,25,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
10,Twins (3),11 (32),31,30,29,28,27,26,25,24,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
11,Rockies (0),12 (31),30,29,28,27,26,25,24,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Blue Jays (2),13 (30),29,28,27,26,25,24,23,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Rays (0),14 (27),26,25,24,23,22,21,20,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Diamondbacks (1),15 (23),22,21,20,19,18,17,16,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Angels (1),16 (22),21,20,19,18,17,16,15,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Marlins (2),17 (21),20,19,18,17,16,15,14,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,White Sox (3),18 (19),18,17,16,15,14,13,12,11,...,7,6,5,4,3,2,1,0,2*,1*
18,Phillies (2),19 (16),15,14,13,12,11,10,9,8,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
19,Yankees (27),20 (15),14,13,12,11,10,9,8,7,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
20,Cardinals (11),21 (13),12,11,10,9,8,7,6,5,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
21,Giants (8),22 (10),9,8,7,6,5,4,3,2,...,8,7,6,5,4,3,2,1,0,1*
22,Royals (2),23 (9),8,7,6,5,4,3,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Cubs (3),24 (8),7,6,5,4,3,2,1,0,...,5,4,3,2,1,0,0,3*,2*,1*
24,Red Sox (9),25 (6),5,4,3,2,1,0,4,3,...,1,0,7,6,5,4,3,2,1,0
25,Nationals (1),26 (5),4,3,2,1,0,49,48,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Braves (4),27 (3),2,1,0,25,24,23,22,21,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*
27,Astros (2),28 (2),1,0,4,3,2,1,0,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Rangers (1),29 (1),0,61,60,59,58,57,56,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Dodgers (8),30 (0),3,2,1,0,30,29,28,27,...,10*,9*,8*,7*,6*,5*,4*,3*,2*,1*